#ifndef __KL2EDK_AUTOGEN_Complex_d__
#define __KL2EDK_AUTOGEN_Complex_d__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Complex_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Complex_d'
// Defined at Complex_d.kl:17:1

struct Complex_d
{
  typedef Complex_d &Result;
  typedef Complex_d const &INParam;
  typedef Complex_d &IOParam;
  typedef Complex_d &OUTParam;
  
  Float64 re;
  Float64 im;
};

inline void Traits<Complex_d>::ConstructEmpty( Complex_d &val )
{
  Traits< Float64 >::ConstructEmpty( val.re );
  Traits< Float64 >::ConstructEmpty( val.im );
}
inline void Traits<Complex_d>::ConstructCopy( Complex_d &lhs, Complex_d const &rhs )
{
  Traits< Float64 >::ConstructCopy( lhs.re, rhs.re );
  Traits< Float64 >::ConstructCopy( lhs.im, rhs.im );
}
inline void Traits<Complex_d>::AssignCopy( Complex_d &lhs, Complex_d const &rhs )
{
  Traits< Float64 >::AssignCopy( lhs.re, rhs.re );
  Traits< Float64 >::AssignCopy( lhs.im, rhs.im );
}
inline void Traits<Complex_d>::Destruct( Complex_d &val )
{
  Traits< Float64 >::Destruct( val.im );
  Traits< Float64 >::Destruct( val.re );
}
}}}

#endif // __KL2EDK_AUTOGEN_Complex_d__
