#ifndef __KL2EDK_AUTOGEN_Mat__
#define __KL2EDK_AUTOGEN_Mat__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Mat'
// Defined at Mat.kl:19:1

struct Mat
{
  typedef Mat &Result;
  typedef Mat const &INParam;
  typedef Mat &IOParam;
  typedef Mat &OUTParam;
  
  SInt32 rows;
  SInt32 cols;
  VariableArray< Float32 > vals;
};

inline void Traits<Mat>::ConstructEmpty( Mat &val )
{
  Traits< SInt32 >::ConstructEmpty( val.rows );
  Traits< SInt32 >::ConstructEmpty( val.cols );
  Traits< VariableArray< Float32 > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat>::ConstructCopy( Mat &lhs, Mat const &rhs )
{
  Traits< SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< Float32 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat>::AssignCopy( Mat &lhs, Mat const &rhs )
{
  Traits< SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< Float32 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat>::Destruct( Mat &val )
{
  Traits< VariableArray< Float32 > >::Destruct( val.vals );
  Traits< SInt32 >::Destruct( val.cols );
  Traits< SInt32 >::Destruct( val.rows );
}
}}}

#endif // __KL2EDK_AUTOGEN_Mat__
