#ifndef __KL2EDK_AUTOGEN_Mat33_c__
#define __KL2EDK_AUTOGEN_Mat33_c__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat33_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Vec3_c.h"
#include "Complex.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Mat33_c'
// Defined at Mat33_c.kl:52:1

struct Mat33_c
{
  typedef Mat33_c &Result;
  typedef Mat33_c const &INParam;
  typedef Mat33_c &IOParam;
  typedef Mat33_c &OUTParam;
  
  Vec3_c row0;
  Vec3_c row1;
  Vec3_c row2;
};

inline void Traits<Mat33_c>::ConstructEmpty( Mat33_c &val )
{
  Traits< Vec3_c >::ConstructEmpty( val.row0 );
  Traits< Vec3_c >::ConstructEmpty( val.row1 );
  Traits< Vec3_c >::ConstructEmpty( val.row2 );
}
inline void Traits<Mat33_c>::ConstructCopy( Mat33_c &lhs, Mat33_c const &rhs )
{
  Traits< Vec3_c >::ConstructCopy( lhs.row0, rhs.row0 );
  Traits< Vec3_c >::ConstructCopy( lhs.row1, rhs.row1 );
  Traits< Vec3_c >::ConstructCopy( lhs.row2, rhs.row2 );
}
inline void Traits<Mat33_c>::AssignCopy( Mat33_c &lhs, Mat33_c const &rhs )
{
  Traits< Vec3_c >::AssignCopy( lhs.row0, rhs.row0 );
  Traits< Vec3_c >::AssignCopy( lhs.row1, rhs.row1 );
  Traits< Vec3_c >::AssignCopy( lhs.row2, rhs.row2 );
}
inline void Traits<Mat33_c>::Destruct( Mat33_c &val )
{
  Traits< Vec3_c >::Destruct( val.row2 );
  Traits< Vec3_c >::Destruct( val.row1 );
  Traits< Vec3_c >::Destruct( val.row0 );
}
}}}

#endif // __KL2EDK_AUTOGEN_Mat33_c__
