#ifndef __KL2EDK_AUTOGEN_Mat_c__
#define __KL2EDK_AUTOGEN_Mat_c__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Complex.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Mat_c'
// Defined at Mat_c.kl:19:1

struct Mat_c
{
  typedef Mat_c &Result;
  typedef Mat_c const &INParam;
  typedef Mat_c &IOParam;
  typedef Mat_c &OUTParam;
  
  SInt32 rows;
  SInt32 cols;
  VariableArray< Complex > vals;
};

inline void Traits<Mat_c>::ConstructEmpty( Mat_c &val )
{
  Traits< SInt32 >::ConstructEmpty( val.rows );
  Traits< SInt32 >::ConstructEmpty( val.cols );
  Traits< VariableArray< Complex > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat_c>::ConstructCopy( Mat_c &lhs, Mat_c const &rhs )
{
  Traits< SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< Complex > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_c>::AssignCopy( Mat_c &lhs, Mat_c const &rhs )
{
  Traits< SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< Complex > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_c>::Destruct( Mat_c &val )
{
  Traits< VariableArray< Complex > >::Destruct( val.vals );
  Traits< SInt32 >::Destruct( val.cols );
  Traits< SInt32 >::Destruct( val.rows );
}
}}}

#endif // __KL2EDK_AUTOGEN_Mat_c__
