#ifndef __KL2EDK_AUTOGEN_Mat_i__
#define __KL2EDK_AUTOGEN_Mat_i__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Mat_i'
// Defined at Mat_i.kl:19:1

struct Mat_i
{
  typedef Mat_i &Result;
  typedef Mat_i const &INParam;
  typedef Mat_i &IOParam;
  typedef Mat_i &OUTParam;
  
  SInt32 rows;
  SInt32 cols;
  VariableArray< SInt32 > vals;
};

inline void Traits<Mat_i>::ConstructEmpty( Mat_i &val )
{
  Traits< SInt32 >::ConstructEmpty( val.rows );
  Traits< SInt32 >::ConstructEmpty( val.cols );
  Traits< VariableArray< SInt32 > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat_i>::ConstructCopy( Mat_i &lhs, Mat_i const &rhs )
{
  Traits< SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< SInt32 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_i>::AssignCopy( Mat_i &lhs, Mat_i const &rhs )
{
  Traits< SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< SInt32 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_i>::Destruct( Mat_i &val )
{
  Traits< VariableArray< SInt32 > >::Destruct( val.vals );
  Traits< SInt32 >::Destruct( val.cols );
  Traits< SInt32 >::Destruct( val.rows );
}
}}}

#endif // __KL2EDK_AUTOGEN_Mat_i__
