#ifndef __KL2EDK_AUTOGEN_Mat_d__
#define __KL2EDK_AUTOGEN_Mat_d__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Mat_d'
// Defined at Mat_d.kl:19:1

struct Mat_d
{
  typedef Mat_d &Result;
  typedef Mat_d const &INParam;
  typedef Mat_d &IOParam;
  typedef Mat_d &OUTParam;
  
  SInt32 rows;
  SInt32 cols;
  VariableArray< Float64 > vals;
};

inline void Traits<Mat_d>::ConstructEmpty( Mat_d &val )
{
  Traits< SInt32 >::ConstructEmpty( val.rows );
  Traits< SInt32 >::ConstructEmpty( val.cols );
  Traits< VariableArray< Float64 > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat_d>::ConstructCopy( Mat_d &lhs, Mat_d const &rhs )
{
  Traits< SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< Float64 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_d>::AssignCopy( Mat_d &lhs, Mat_d const &rhs )
{
  Traits< SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< VariableArray< Float64 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_d>::Destruct( Mat_d &val )
{
  Traits< VariableArray< Float64 > >::Destruct( val.vals );
  Traits< SInt32 >::Destruct( val.cols );
  Traits< SInt32 >::Destruct( val.rows );
}
}}}

#endif // __KL2EDK_AUTOGEN_Mat_d__
