#ifndef __KL2EDK_AUTOGEN_Math__
#define __KL2EDK_AUTOGEN_Math__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Math.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

#include "ARGB.h"
#include "Box2.h"
#include "Box3.h"
#include "Color.h"
#include "Complex.h"
#include "Complex_d.h"
#include "Euler.h"
#include "Euler_d.h"
#include "Euler_i.h"
#include "Mat.h"
#include "Mat22.h"
#include "Mat22_c.h"
#include "Mat22_cd.h"
#include "Mat22_d.h"
#include "Mat22_i.h"
#include "Mat33.h"
#include "Mat33_c.h"
#include "Mat33_cd.h"
#include "Mat33_d.h"
#include "Mat33_i.h"
#include "Mat44.h"
#include "Mat44_c.h"
#include "Mat44_cd.h"
#include "Mat44_d.h"
#include "Mat44_i.h"
#include "Mat_c.h"
#include "Mat_cd.h"
#include "Mat_d.h"
#include "Mat_i.h"
#include "Quat.h"
#include "Quat_d.h"
#include "Quat_i.h"
#include "RGB.h"
#include "RGBA.h"
#include "Ray.h"
#include "RotationOrder.h"
#include "Vec.h"
#include "Vec2.h"
#include "Vec2_c.h"
#include "Vec2_cd.h"
#include "Vec2_d.h"
#include "Vec2_i.h"
#include "Vec3.h"
#include "Vec3_c.h"
#include "Vec3_cd.h"
#include "Vec3_d.h"
#include "Vec3_i.h"
#include "Vec4.h"
#include "Vec4_c.h"
#include "Vec4_cd.h"
#include "Vec4_d.h"
#include "Vec4_i.h"
#include "Vec_c.h"
#include "Vec_cd.h"
#include "Vec_d.h"
#include "Vec_i.h"
#include "Xfo.h"
#include "global_functions.h"

#endif // __KL2EDK_AUTOGEN_Math__
