#ifndef __KL2EDK_AUTOGEN_Vec__
#define __KL2EDK_AUTOGEN_Vec__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Vec'
// Defined at Vec.kl:19:1

struct Vec
{
  typedef Vec &Result;
  typedef Vec const &INParam;
  typedef Vec &IOParam;
  typedef Vec &OUTParam;
  
  VariableArray< Float32 > vals;
};

inline void Traits<Vec>::ConstructEmpty( Vec &val )
{
  Traits< VariableArray< Float32 > >::ConstructEmpty( val.vals );
}
inline void Traits<Vec>::ConstructCopy( Vec &lhs, Vec const &rhs )
{
  Traits< VariableArray< Float32 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec>::AssignCopy( Vec &lhs, Vec const &rhs )
{
  Traits< VariableArray< Float32 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec>::Destruct( Vec &val )
{
  Traits< VariableArray< Float32 > >::Destruct( val.vals );
}
}}}

#endif // __KL2EDK_AUTOGEN_Vec__
