#ifndef __KL2EDK_AUTOGEN_Vec4_c__
#define __KL2EDK_AUTOGEN_Vec4_c__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec4_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.4.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 4
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Complex.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Vec4_c'
// Defined at Vec4_c.kl:19:1

struct Vec4_c
{
  typedef Vec4_c &Result;
  typedef Vec4_c const &INParam;
  typedef Vec4_c &IOParam;
  typedef Vec4_c &OUTParam;
  
  Complex x;
  Complex y;
  Complex z;
  Complex t;
};

inline void Traits<Vec4_c>::ConstructEmpty( Vec4_c &val )
{
  Traits< Complex >::ConstructEmpty( val.x );
  Traits< Complex >::ConstructEmpty( val.y );
  Traits< Complex >::ConstructEmpty( val.z );
  Traits< Complex >::ConstructEmpty( val.t );
}
inline void Traits<Vec4_c>::ConstructCopy( Vec4_c &lhs, Vec4_c const &rhs )
{
  Traits< Complex >::ConstructCopy( lhs.x, rhs.x );
  Traits< Complex >::ConstructCopy( lhs.y, rhs.y );
  Traits< Complex >::ConstructCopy( lhs.z, rhs.z );
  Traits< Complex >::ConstructCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_c>::AssignCopy( Vec4_c &lhs, Vec4_c const &rhs )
{
  Traits< Complex >::AssignCopy( lhs.x, rhs.x );
  Traits< Complex >::AssignCopy( lhs.y, rhs.y );
  Traits< Complex >::AssignCopy( lhs.z, rhs.z );
  Traits< Complex >::AssignCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_c>::Destruct( Vec4_c &val )
{
  Traits< Complex >::Destruct( val.t );
  Traits< Complex >::Destruct( val.z );
  Traits< Complex >::Destruct( val.y );
  Traits< Complex >::Destruct( val.x );
}
}}}

#endif // __KL2EDK_AUTOGEN_Vec4_c__
