#ifndef __KL2EDK_AUTOGEN_Vec4_cd__
#define __KL2EDK_AUTOGEN_Vec4_cd__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec4_cd.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Complex_d.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Vec4_cd'
// Defined at Vec4_cd.kl:19:1

struct Vec4_cd
{
  typedef Vec4_cd &Result;
  typedef Vec4_cd const &INParam;
  typedef Vec4_cd &IOParam;
  typedef Vec4_cd &OUTParam;
  
  Complex_d x;
  Complex_d y;
  Complex_d z;
  Complex_d t;
};

inline void Traits<Vec4_cd>::ConstructEmpty( Vec4_cd &val )
{
  Traits< Complex_d >::ConstructEmpty( val.x );
  Traits< Complex_d >::ConstructEmpty( val.y );
  Traits< Complex_d >::ConstructEmpty( val.z );
  Traits< Complex_d >::ConstructEmpty( val.t );
}
inline void Traits<Vec4_cd>::ConstructCopy( Vec4_cd &lhs, Vec4_cd const &rhs )
{
  Traits< Complex_d >::ConstructCopy( lhs.x, rhs.x );
  Traits< Complex_d >::ConstructCopy( lhs.y, rhs.y );
  Traits< Complex_d >::ConstructCopy( lhs.z, rhs.z );
  Traits< Complex_d >::ConstructCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_cd>::AssignCopy( Vec4_cd &lhs, Vec4_cd const &rhs )
{
  Traits< Complex_d >::AssignCopy( lhs.x, rhs.x );
  Traits< Complex_d >::AssignCopy( lhs.y, rhs.y );
  Traits< Complex_d >::AssignCopy( lhs.z, rhs.z );
  Traits< Complex_d >::AssignCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_cd>::Destruct( Vec4_cd &val )
{
  Traits< Complex_d >::Destruct( val.t );
  Traits< Complex_d >::Destruct( val.z );
  Traits< Complex_d >::Destruct( val.y );
  Traits< Complex_d >::Destruct( val.x );
}
}}}

#endif // __KL2EDK_AUTOGEN_Vec4_cd__
