#ifndef __KL2EDK_AUTOGEN_Vec_i__
#define __KL2EDK_AUTOGEN_Vec_i__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.4.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 4
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Vec_i'
// Defined at Vec_i.kl:19:1

struct Vec_i
{
  typedef Vec_i &Result;
  typedef Vec_i const &INParam;
  typedef Vec_i &IOParam;
  typedef Vec_i &OUTParam;
  
  VariableArray< SInt32 > vals;
};

inline void Traits<Vec_i>::ConstructEmpty( Vec_i &val )
{
  Traits< VariableArray< SInt32 > >::ConstructEmpty( val.vals );
}
inline void Traits<Vec_i>::ConstructCopy( Vec_i &lhs, Vec_i const &rhs )
{
  Traits< VariableArray< SInt32 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_i>::AssignCopy( Vec_i &lhs, Vec_i const &rhs )
{
  Traits< VariableArray< SInt32 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_i>::Destruct( Vec_i &val )
{
  Traits< VariableArray< SInt32 > >::Destruct( val.vals );
}
}}}

#endif // __KL2EDK_AUTOGEN_Vec_i__
