#ifndef __KL2EDK_AUTOGEN_Vec_cd__
#define __KL2EDK_AUTOGEN_Vec_cd__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec_cd.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.4.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 4
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Complex_d.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Vec_cd'
// Defined at Vec_cd.kl:19:1

struct Vec_cd
{
  typedef Vec_cd &Result;
  typedef Vec_cd const &INParam;
  typedef Vec_cd &IOParam;
  typedef Vec_cd &OUTParam;
  
  VariableArray< Complex_d > vals;
};

inline void Traits<Vec_cd>::ConstructEmpty( Vec_cd &val )
{
  Traits< VariableArray< Complex_d > >::ConstructEmpty( val.vals );
}
inline void Traits<Vec_cd>::ConstructCopy( Vec_cd &lhs, Vec_cd const &rhs )
{
  Traits< VariableArray< Complex_d > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_cd>::AssignCopy( Vec_cd &lhs, Vec_cd const &rhs )
{
  Traits< VariableArray< Complex_d > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_cd>::Destruct( Vec_cd &val )
{
  Traits< VariableArray< Complex_d > >::Destruct( val.vals );
}
}}}

#endif // __KL2EDK_AUTOGEN_Vec_cd__
