#ifndef __KL2EDK_AUTOGEN_Vec_d__
#define __KL2EDK_AUTOGEN_Vec_d__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.3.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 3
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Vec_d'
// Defined at Vec_d.kl:19:1

struct Vec_d
{
  typedef Vec_d &Result;
  typedef Vec_d const &INParam;
  typedef Vec_d &IOParam;
  typedef Vec_d &OUTParam;
  
  VariableArray< Float64 > vals;
};

inline void Traits<Vec_d>::ConstructEmpty( Vec_d &val )
{
  Traits< VariableArray< Float64 > >::ConstructEmpty( val.vals );
}
inline void Traits<Vec_d>::ConstructCopy( Vec_d &lhs, Vec_d const &rhs )
{
  Traits< VariableArray< Float64 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_d>::AssignCopy( Vec_d &lhs, Vec_d const &rhs )
{
  Traits< VariableArray< Float64 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_d>::Destruct( Vec_d &val )
{
  Traits< VariableArray< Float64 > >::Destruct( val.vals );
}
}}}

#endif // __KL2EDK_AUTOGEN_Vec_d__
